### PR TITLE
Add support for Windows on ARM64

### LINKED ISSUE #174: Win10 ARM version ?
**Is your feature request related to a problem? Please describe.**
I am developing Excel VBA projects for use on both Windows and Mac machines. Since the introduction of the M1 Macs, the only possibility to run Windows on a VM on my Mac is through the ARM version (from the Insider program). It appears the RibbonX installer I downloaded requires an x64 architecture ...

**Describe the solution you'd like**
Is it possible to get a version out that supports Win10 ARM as well ?

**Describe alternatives you've considered**
I am new to RibbonX and don't know if any alternatives exist for ARM-based Office 365 on Win10. If there are, I'd be happy to explore those ...

**Additional context**
I'm happy to contribute in translation support (I am native Dutch speaker, and fairly fluent in German and French), please let me know if this is of interest to you.

### PR DESCRIPTION
**Pull request by fernandreu**
Closes #174

### CODE REVIEW

**Comment by rfn6** [comment]
I'm fairly unfamiliar with GitHub, how would I download the latest version that's compatible with Windows ARM? I saw you merged it into the master, so I'm assuming it works now?

**Comment by fernandreu** [comment]
You can download it from here:
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1154&view=artifacts&pathAsName=false&type=publishedArtifacts

As far as I can tell, yes, the build runs fine on Windows ARM64, but I can always do additional tweaks if needed.

**Comment by nvcken** [comment]
Hi @fernandreu how can download the build than can run on Win ARM64 ?
Tried the link, but don't find any download file
image

**Comment by nvcken** [comment]
I can see and download the ARM installer file after click around Pipelines / Build / Artifacts now. Thanks

**Pull request merged**
