### PR TITLE
Update Strings.zh-CN.resx

### PR DESCRIPTION
**Pull request by bitaller**
- Translate “Translators” to Chinese
- Optimize some words of translation

### CODE REVIEW

**Comment by fernandreu** [comment]
Sorry, I did not realise you sent this a few days ago. Merged now

**Comment by bitaller** [comment]
No worry. When will users get new release (v 1.8)? I'm going to introduce the software and project on ExcelHome (http://club.excelhome.net/) which is the biggest Office online community. It has more than 5M registered users.

**Comment by fernandreu** [comment]
I'll aim to do the release at some point this weekend. I have changed a bit the way in which the tool is packaged, plus added a few more .NET 5 alternatives, so I'll spend a bit of time making sure they all work fine first

**Comment by fernandreu** [comment]
That's the v1.8 released ([here](https://github.com/fernandreu/office-ribbonx-editor/releases/tag/v1.8.0)). If you have any issues, just let me know (either here or in a new issue).

**Pull request merged**
